<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Hands-on Lab: Complete the EDA with SQL</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [12]:
#!pip install sqlalchemy==1.4
#!pip install ipython-sql
#!pip install pandas
!pip install --upgrade ipython-sql prettytable

Requirement already satisfied: ipython-sql in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.17.0)
Requirement already satisfied: ipython in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython-sql) (9.6.0)
Requirement already satisfied: sqlalchemy>=2.0 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython-sql) (2.0.49)
Requirement already satisfied: sqlparse in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from prettytable) (0.2.14)
Requirement already satisfied: greenlet>=1 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: colorama in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.16 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in C:\Users\colin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data->ipython->ipython-sql) (0.2.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [5]:
%load_ext sql

In [6]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [7]:
%sql sqlite:///my_data1.db

In [8]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

101

**Note:This below code is added to remove blank rows from table**

In [9]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Done.

[]

In [13]:
%config SqlMagic.autopandas = True
df = pd.read_sql("SELECT * FROM SPACEXTABLE", con)
df.head()

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"** . 

   

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [14]:
pd.read_sql("SELECT DISTINCT Launch_Site FROM SPACEXTABLE ",con)

    Launch_Site
0   CCAFS LC-40
1   VAFB SLC-4E
2    KSC LC-39A
3  CCAFS SLC-40


### Task 2


#####  Display 5 records where launch sites begin with the string 'KSC'

In [15]:
pd.read_sql("SELECT * FROM SPACEXTABLE WHERE Launch_Site LIKE 'KSC%' LIMIT 5",con)

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2017-02-19,14:39:00,F9 FT B1031.1,KSC LC-39A,SpaceX CRS-10,2490,LEO (ISS),NASA (CRS),Success,Success (ground pad)
1,2017-03-16,6:00:00,F9 FT B1030,KSC LC-39A,EchoStar 23,5600,GTO,EchoStar,Success,No attempt
2,2017-03-30,22:27:00,F9 FT B1021.2,KSC LC-39A,SES-10,5300,GTO,SES,Success,Success (drone ship)
3,2017-05-01,11:15:00,F9 FT B1032.1,KSC LC-39A,NROL-76,5300,LEO,NRO,Success,Success (ground pad)
4,2017-05-15,23:21:00,F9 FT B1034,KSC LC-39A,Inmarsat-5 F4,6070,GTO,Inmarsat,Success,No attempt

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [16]:
pd.read_sql("SELECT SUM(PAYLOAD_MASS__KG_) AS 'Total Payload Mass' FROM SPACEXTABLE WHERE Customer = 'NASA (CRS)'",con)

   Total Payload Mass
0               45596

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [27]:
pd.read_sql("SELECT AVG(PAYLOAD_MASS__KG_) AS 'Average Payload Mass by booster F9 v1.1' FROM SPACEXTABLE WHERE Booster_Version LIKE '%F9 v1.1%'",con)

   Average Payload Mass by booster F9 v1.1
0                              2534.666667

### Task 5

##### List the date where the succesful landing outcome in drone ship was acheived.


_Hint:Use min function_

In [18]:
pd.read_sql("SELECT MIN(Date) AS 'Drone ship success date' FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (drone ship)'",con)

  Drone ship success date
0              2016-04-08

In [19]:
pd.read_sql("SELECT COUNT(*) AS 'Drone ship successes' FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (drone ship)'",con)

   Drone ship successes
0                    14

### Task 6

##### List the names of the boosters which have success in ground pad  and have payload mass greater than 4000 but less than 6000

In [21]:
pd.read_sql("SELECT Booster_Version FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (ground pad)' AND PAYLOAD_MASS__KG_ > 4000 AND PAYLOAD_MASS__KG_ < 6000",con)

  Booster_Version
0   F9 FT B1032.1
1   F9 B4 B1040.1
2   F9 B4 B1043.1

### Task 7




##### List the total number of successful and failure mission outcomes

In [22]:
pd.read_sql("SELECT Mission_Outcome, COUNT(*) AS Count FROM SPACEXTABLE GROUP BY Mission_Outcome;",con)

                    Mission_Outcome  Count
0               Failure (in flight)      1
1                           Success     98
2                          Success       1
3  Success (payload status unclear)      1

### Task 8



##### List all the booster_versions that have carried the maximum payload mass. Use a subquery.

In [23]:
pd.read_sql("SELECT Booster_Version FROM SPACEXTABLE WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTABLE);",con)

   Booster_Version
0    F9 B5 B1048.4
1    F9 B5 B1049.4
2    F9 B5 B1051.3
3    F9 B5 B1056.4
4    F9 B5 B1048.5
5    F9 B5 B1051.4
6    F9 B5 B1049.5
7   F9 B5 B1060.2
8   F9 B5 B1058.3
9    F9 B5 B1051.6
10   F9 B5 B1060.3
11  F9 B5 B1049.7

### Task 9


##### List the records which will display the month names, succesful landing_outcomes in ground pad ,booster versions, launch_site for the months in year 2017
**Note: SQLLite does not support monthnames. So you need to use substr(Date,6,2) for month, substr(Date,9,2) for date, substr(Date,0,5),='2017' for year.**

In [ ]:
pd.read_sql("SELECT CASE substr(Date, 6, 2) WHEN '01' THEN 'January'         WHEN '02' THEN 'February' WHEN '03' THEN 'March' WHEN '04' THEN 'April' WHEN '05' THEN 'May' WHEN '06' THEN 'June' WHEN '07' THEN 'July'         WHEN '08' THEN 'August'         WHEN '09' THEN 'September'         WHEN '10' THEN 'October'         WHEN '11' THEN 'November'         WHEN '12' THEN 'December'     END AS Month,     Landing_Outcome,     Booster_Version,     Launch_Site FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (ground pad)' AND substr(Date, 1, 4) = '2017';",con)

       Month       Landing_Outcome Booster_Version   Launch_Site
0   February  Success (ground pad)   F9 FT B1031.1    KSC LC-39A
1        May  Success (ground pad)   F9 FT B1032.1    KSC LC-39A
2       June  Success (ground pad)   F9 FT B1035.1    KSC LC-39A
3     August  Success (ground pad)   F9 B4 B1039.1    KSC LC-39A
4  September  Success (ground pad)   F9 B4 B1040.1    KSC LC-39A
5   December  Success (ground pad)  F9 FT  B1035.2  CCAFS SLC-40

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order

In [26]:
pd.read_sql("SELECT Landing_Outcome, COUNT(*) AS Count FROM SPACEXTABLE WHERE Date BETWEEN '2010-06-04' AND '2017-03-20' GROUP BY Landing_Outcome ORDER BY Count DESC;",con)

          Landing_Outcome  Count
0              No attempt     10
1    Success (drone ship)      5
2    Failure (drone ship)      5
3    Success (ground pad)      3
4      Controlled (ocean)      3
5    Uncontrolled (ocean)      2
6     Failure (parachute)      2
7  Precluded (drone ship)      1

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%203/LAB-String_Patterns_Sorting_Grouping.md.html">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

<!--## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |
--!>

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>